### ISSUE TITLE
Issue with converting to Unreal Engine 5.3.2

### ISSUE THREAD

**Issue by MaxiKitti** [hippowombat/Source2StyleSmoke#1]
I wanted to credit you and use this for my game im going to create but i cant seem to rebuild the actor and it always breaks if i use it in anything other that unreal engine 5.0.3, the niagra particle also partially breaks but i think i can fix that on my own

**Comment by hippowombat** [comment]
> I wanted to credit you and use this for my game im going to create but i cant seem to rebuild the actor and it always breaks if i use it in anything other that unreal engine 5.0.3, the niagra particle also partially breaks but i think i can fix that on my own

Hey there, I'll spin this up in 5.3 when I get back to my desk & see if I can repro/solve.

Thanks for highlighting this!

**Comment by MaxiKitti** [comment]
Omg thank you so much and the immedate feedback too! ive been pulling my hair out researching voxels, adaptive voxels, particle systems and doing real world recording and research and yours has been the closest thing ive seen other than a unity version

**Comment by MaxiKitti** [comment]
not to rush but hows it coming along?

**Comment by hippowombat** [comment]
Hey there, I apologize for the slow turnaround on this, I just pulled & updated the project to 5.3.2 on my end and was able to build & launch the editor no problem. I've added a 5.3 branch to this repo, can you pull from that & see if it works for you? If not we can definitely troubleshoot further. https://github.com/hippowombat/Source2StyleSmoke/tree/5dot3dot2

**Comment by MaxiKitti** [comment]
alright thank you for helping out i wasnt able to test it bc i had to upgrade to 64gb of ram, ill be testing it today ^w^

**Comment by MaxiKitti** [comment]
thank you so much! it works perfectly as a separate project, but it seems not to work when i transfer it over to my current project is there a way to fix this issue like a plugin not enabled or something i needed to import over? (i didnt import the first person gun bp and a lot of the conflicting first person project files so maybe that could be the reason maybe)

https://github.com/hippowombat/Source2StyleSmoke/assets/98273834/46090d18-b7f7-4770-9bca-f8d187fdaa69

**Comment by MaxiKitti** [comment]
all i can really tell is it cant read or find something or somethings missing

**Comment by hippowombat** [comment]
Hmmmm, there is a dependency on some C++ code contained in the Source folder, were you able to port that over & change the API reference info over to point to your project?

**Comment by MaxiKitti** [comment]
could to reference me over to a tutorial or send a video of how once could transfer the c++ code? im not quite sure of how to do that

**Comment by MaxiKitti** [comment]
actually give me till 19-20th of june imma try out somethings on my live stream, i see you live stream on twitch so imma check you out next time your live. but imma close this bc im pretty sure ik what the problem is on my end i will follow tutorials to figure it out thank you again for your help ^w^

**Comment by hippowombat** [comment]
No problem! If you'd like any additional assistance please let me know, you can add me on Discord & reach out any time, my username there is Hippowombat.

Cheers!
